/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project;

import se.michaelthelin.spotify.SpotifyApi;

public class App {

//    public String getGreeting() {
//        return "Hello World!";
//    }

    public static void main(String[] args) {
//        System.out.println(new App().getGreeting());

        SpotifyApi spotifyApi = new SpotifyApi.Builder()
                .setAccessToken("token-goes-here")
                .build();

        spotifyApi.getTrack("4cOdK2wGLETKBW3PvgPWqT?si=1af93b96145e4d6d");

    }
}
